[2023-07-31 00:00:37,023] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: hello_world.send_email scheduled__2017-03-29T00:00:00+00:00 [queued]>
[2023-07-31 00:00:37,101] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: hello_world.send_email scheduled__2017-03-29T00:00:00+00:00 [queued]>
[2023-07-31 00:00:37,101] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-07-31 00:00:37,101] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2023-07-31 00:00:37,104] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-07-31 00:00:37,172] {taskinstance.py:1397} INFO - Executing <Task(EmailOperator): send_email> on 2017-03-29 00:00:00+00:00
[2023-07-31 00:00:37,191] {standard_task_runner.py:52} INFO - Started process 6483 to run task
[2023-07-31 00:00:37,198] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'hello_world', 'send_email', 'scheduled__2017-03-29T00:00:00+00:00', '--job-id', '355', '--raw', '--subdir', 'DAGS_FOLDER/dag_smtp_test.py', '--cfg-path', '/tmp/tmpi0gxuolf', '--error-file', '/tmp/tmps5km0ztk']
[2023-07-31 00:00:37,199] {standard_task_runner.py:80} INFO - Job 355: Subtask send_email
[2023-07-31 00:00:38,509] {task_command.py:371} INFO - Running <TaskInstance: hello_world.send_email scheduled__2017-03-29T00:00:00+00:00 [running]> on host b0e2d990d7ae
[2023-07-31 00:00:39,660] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=hello_world
AIRFLOW_CTX_TASK_ID=send_email
AIRFLOW_CTX_EXECUTION_DATE=2017-03-29T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2017-03-29T00:00:00+00:00
[2023-07-31 00:00:39,778] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/email.py:119: PendingDeprecationWarning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
  send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)

[2023-07-31 00:00:39,778] {configuration.py:552} WARNING - section/key [smtp/smtp_user] not found in config
[2023-07-31 00:00:39,778] {email.py:228} INFO - Email alerting: attempt 1
[2023-07-31 00:00:39,779] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/email.py", line 85, in execute
    custom_headers=self.custom_headers,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 71, in send_email
    **kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 119, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 230, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 264, in _get_smtp_connection
    else smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/usr/local/lib/python3.7/smtplib.py", line 251, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.7/smtplib.py", line 336, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.7/smtplib.py", line 307, in _get_socket
    self.source_address)
  File "/usr/local/lib/python3.7/socket.py", line 728, in create_connection
    raise err
  File "/usr/local/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address
[2023-07-31 00:00:39,809] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=hello_world, task_id=send_email, execution_date=20170329T000000, start_date=20230731T000037, end_date=20230731T000039
[2023-07-31 00:00:39,905] {standard_task_runner.py:97} ERROR - Failed to execute job 355 for task send_email ([Errno 99] Cannot assign requested address; 6483)
[2023-07-31 00:00:39,964] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-07-31 00:00:40,278] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
