[2023-08-01 02:01:46,114] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: etl_api_marvel_hacia_aws_redshift_multitask.cargar_data scheduled__2023-08-01T01:59:37.497628+00:00 [queued]>
[2023-08-01 02:01:46,137] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: etl_api_marvel_hacia_aws_redshift_multitask.cargar_data scheduled__2023-08-01T01:59:37.497628+00:00 [queued]>
[2023-08-01 02:01:46,137] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-08-01 02:01:46,137] {taskinstance.py:1377} INFO - Starting attempt 1 of 11
[2023-08-01 02:01:46,137] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-08-01 02:01:46,221] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): cargar_data> on 2023-08-01 01:59:37.497628+00:00
[2023-08-01 02:01:46,242] {standard_task_runner.py:52} INFO - Started process 2086 to run task
[2023-08-01 02:01:46,251] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'etl_api_marvel_hacia_aws_redshift_multitask', 'cargar_data', 'scheduled__2023-08-01T01:59:37.497628+00:00', '--job-id', '676', '--raw', '--subdir', 'DAGS_FOLDER/dag_etl_multiple_tasks.py', '--cfg-path', '/tmp/tmp3nmky8ol', '--error-file', '/tmp/tmphlivoff5']
[2023-08-01 02:01:46,266] {standard_task_runner.py:80} INFO - Job 676: Subtask cargar_data
[2023-08-01 02:01:46,698] {task_command.py:371} INFO - Running <TaskInstance: etl_api_marvel_hacia_aws_redshift_multitask.cargar_data scheduled__2023-08-01T01:59:37.497628+00:00 [running]> on host 24cbf2f01ed0
[2023-08-01 02:01:47,040] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=arielmfeldman.af@gmail.com
AIRFLOW_CTX_DAG_OWNER=Ariel Feldman
AIRFLOW_CTX_DAG_ID=etl_api_marvel_hacia_aws_redshift_multitask
AIRFLOW_CTX_TASK_ID=cargar_data
AIRFLOW_CTX_EXECUTION_DATE=2023-08-01T01:59:37.497628+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-08-01T01:59:37.497628+00:00
[2023-08-01 02:01:47,089] {logging_mixin.py:115} INFO - Columnas en load data
[2023-08-01 02:01:47,097] {logging_mixin.py:115} INFO -  Index(['id_character', 'nombre', 'descripcion', 'cantidad_de_comics',
       'cantidad_de_series', 'cantidad_de_historias', 'fecha_modificacion',
       'fecha_insercion_bd'],
      dtype='object')
[2023-08-01 02:01:59,719] {python.py:173} INFO - Done. Returned value was: None
[2023-08-01 02:01:59,753] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=etl_api_marvel_hacia_aws_redshift_multitask, task_id=cargar_data, execution_date=20230801T015937, start_date=20230801T020146, end_date=20230801T020159
[2023-08-01 02:01:59,819] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-08-01 02:01:59,863] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/email.py:119: PendingDeprecationWarning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
  send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)

[2023-08-01 02:01:59,864] {configuration.py:552} WARNING - section/key [smtp/smtp_user] not found in config
[2023-08-01 02:01:59,864] {email.py:228} INFO - Email alerting: attempt 1
[2023-08-01 02:01:59,865] {taskinstance.py:1760} ERROR - Error when executing on_success_callback
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1758, in _run_finished_callback
    task.on_success_callback(context)
  File "/opt/airflow/dags/dag_etl_multiple_tasks.py", line 26, in success_email_function
    send_email(to=smtp_env['EMAIL'], subject=subject, html_content=msg)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 71, in send_email
    **kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 119, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 230, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 264, in _get_smtp_connection
    else smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/usr/local/lib/python3.7/smtplib.py", line 251, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.7/smtplib.py", line 336, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.7/smtplib.py", line 307, in _get_socket
    self.source_address)
  File "/usr/local/lib/python3.7/socket.py", line 728, in create_connection
    raise err
  File "/usr/local/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address
[2023-08-01 02:01:59,911] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
