[2023-07-13 21:11:10,290] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: mi_primer_dag_v3.tercera_tarea scheduled__2022-11-22T00:00:00+00:00 [queued]>
[2023-07-13 21:11:10,672] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: mi_primer_dag_v3.tercera_tarea scheduled__2022-11-22T00:00:00+00:00 [queued]>
[2023-07-13 21:11:10,798] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-07-13 21:11:10,798] {taskinstance.py:1377} INFO - Starting attempt 1 of 6
[2023-07-13 21:11:10,798] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-07-13 21:11:11,295] {taskinstance.py:1397} INFO - Executing <Task(BashOperator): tercera_tarea> on 2022-11-22 00:00:00+00:00
[2023-07-13 21:11:11,417] {standard_task_runner.py:52} INFO - Started process 1838 to run task
[2023-07-13 21:11:11,433] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'mi_primer_dag_v3', 'tercera_tarea', 'scheduled__2022-11-22T00:00:00+00:00', '--job-id', '353', '--raw', '--subdir', 'DAGS_FOLDER/primer_dag_v3.py', '--cfg-path', '/tmp/tmpx_am995s', '--error-file', '/tmp/tmp_ffcf099']
[2023-07-13 21:11:11,454] {standard_task_runner.py:80} INFO - Job 353: Subtask tercera_tarea
[2023-07-13 21:11:12,651] {task_command.py:371} INFO - Running <TaskInstance: mi_primer_dag_v3.tercera_tarea scheduled__2022-11-22T00:00:00+00:00 [running]> on host 7a1b6d75866e
[2023-07-13 21:11:14,340] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Ari Feldman
AIRFLOW_CTX_DAG_ID=mi_primer_dag_v3
AIRFLOW_CTX_TASK_ID=tercera_tarea
AIRFLOW_CTX_EXECUTION_DATE=2022-11-22T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-22T00:00:00+00:00
[2023-07-13 21:11:14,349] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2023-07-13 21:11:14,373] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'echo hola, soy la tarea 3 y sere corrida luego de Tarea 1 al mismo tiempo que Tarea 2']
[2023-07-13 21:11:15,762] {subprocess.py:85} INFO - Output:
[2023-07-13 21:11:16,049] {subprocess.py:92} INFO - hola, soy la tarea 3 y sere corrida luego de Tarea 1 al mismo tiempo que Tarea 2
[2023-07-13 21:11:16,050] {subprocess.py:96} INFO - Command exited with return code 0
[2023-07-13 21:11:16,895] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=mi_primer_dag_v3, task_id=tercera_tarea, execution_date=20221122T000000, start_date=20230713T211110, end_date=20230713T211116
[2023-07-13 21:11:17,546] {local_task_job.py:221} WARNING - State of this instance has been externally set to success. Terminating instance.
[2023-07-13 21:11:17,557] {process_utils.py:129} INFO - Sending Signals.SIGTERM to group 1838. PIDs of all processes in the group: [1838]
[2023-07-13 21:11:17,557] {process_utils.py:80} INFO - Sending the signal Signals.SIGTERM to group 1838
[2023-07-13 21:11:17,567] {taskinstance.py:1561} ERROR - Received SIGTERM. Terminating subprocesses.
[2023-07-13 21:11:17,568] {subprocess.py:103} INFO - Sending SIGTERM signal to process group
[2023-07-13 21:11:17,600] {standard_task_runner.py:97} ERROR - Failed to execute job 353 for task tercera_tarea ([Errno 3] No such process; 1838)
[2023-07-13 21:11:18,013] {process_utils.py:75} INFO - Process psutil.Process(pid=1838, status='terminated', exitcode=1, started='21:11:10') (1838) terminated with exit code 1
