[2023-08-01 23:27:58,779] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: etl_api_marvel_2.transform manual__2023-08-01T23:27:53.960360+00:00 [queued]>
[2023-08-01 23:27:58,797] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: etl_api_marvel_2.transform manual__2023-08-01T23:27:53.960360+00:00 [queued]>
[2023-08-01 23:27:58,797] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-08-01 23:27:58,798] {taskinstance.py:1377} INFO - Starting attempt 1 of 2
[2023-08-01 23:27:58,798] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-08-01 23:27:58,817] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): transform> on 2023-08-01 23:27:53.960360+00:00
[2023-08-01 23:27:58,825] {standard_task_runner.py:52} INFO - Started process 2107 to run task
[2023-08-01 23:27:58,830] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'etl_api_marvel_2', 'transform', 'manual__2023-08-01T23:27:53.960360+00:00', '--job-id', '1274', '--raw', '--subdir', 'DAGS_FOLDER/dag_etl_failure.py', '--cfg-path', '/tmp/tmpyehdxu2z', '--error-file', '/tmp/tmpt1zjkk1s']
[2023-08-01 23:27:58,832] {standard_task_runner.py:80} INFO - Job 1274: Subtask transform
[2023-08-01 23:27:58,916] {task_command.py:371} INFO - Running <TaskInstance: etl_api_marvel_2.transform manual__2023-08-01T23:27:53.960360+00:00 [running]> on host 24cbf2f01ed0
[2023-08-01 23:27:59,021] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=arielmfeldman.af@gmail.com
AIRFLOW_CTX_DAG_OWNER=Ariel Feldman
AIRFLOW_CTX_DAG_ID=etl_api_marvel_2
AIRFLOW_CTX_TASK_ID=transform
AIRFLOW_CTX_EXECUTION_DATE=2023-08-01T23:27:53.960360+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-08-01T23:27:53.960360+00:00
[2023-08-01 23:27:59,095] {python.py:173} INFO - Done. Returned value was: None
[2023-08-01 23:27:59,118] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=etl_api_marvel_2, task_id=transform, execution_date=20230801T232753, start_date=20230801T232758, end_date=20230801T232759
[2023-08-01 23:27:59,163] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-08-01 23:27:59,201] {taskinstance.py:1760} ERROR - Error when executing on_success_callback
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1758, in _run_finished_callback
    task.on_success_callback(context)
TypeError: send_email() missing 1 required positional argument: 'context'
[2023-08-01 23:27:59,222] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
