[2023-08-01 03:25:42,573] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: etl_api_marvel_hacia_aws_redshift_multitask.cargar_data scheduled__2023-08-01T03:23:35.277444+00:00 [queued]>
[2023-08-01 03:25:42,608] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: etl_api_marvel_hacia_aws_redshift_multitask.cargar_data scheduled__2023-08-01T03:23:35.277444+00:00 [queued]>
[2023-08-01 03:25:42,609] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-08-01 03:25:42,609] {taskinstance.py:1377} INFO - Starting attempt 1 of 11
[2023-08-01 03:25:42,609] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-08-01 03:25:42,655] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): cargar_data> on 2023-08-01 03:23:35.277444+00:00
[2023-08-01 03:25:42,668] {standard_task_runner.py:52} INFO - Started process 6065 to run task
[2023-08-01 03:25:42,677] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'etl_api_marvel_hacia_aws_redshift_multitask', 'cargar_data', 'scheduled__2023-08-01T03:23:35.277444+00:00', '--job-id', '796', '--raw', '--subdir', 'DAGS_FOLDER/dag_etl_multiple_tasks.py', '--cfg-path', '/tmp/tmpoaali882', '--error-file', '/tmp/tmp_juodp51']
[2023-08-01 03:25:42,679] {standard_task_runner.py:80} INFO - Job 796: Subtask cargar_data
[2023-08-01 03:25:42,909] {task_command.py:371} INFO - Running <TaskInstance: etl_api_marvel_hacia_aws_redshift_multitask.cargar_data scheduled__2023-08-01T03:23:35.277444+00:00 [running]> on host 24cbf2f01ed0
[2023-08-01 03:25:43,132] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=arielmfeldman.af@gmail.com
AIRFLOW_CTX_DAG_OWNER=Ariel Feldman
AIRFLOW_CTX_DAG_ID=etl_api_marvel_hacia_aws_redshift_multitask
AIRFLOW_CTX_TASK_ID=cargar_data
AIRFLOW_CTX_EXECUTION_DATE=2023-08-01T03:23:35.277444+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-08-01T03:23:35.277444+00:00
[2023-08-01 03:25:43,171] {logging_mixin.py:115} INFO - Columnas en load data
[2023-08-01 03:25:43,174] {logging_mixin.py:115} INFO -  Index(['id_character', 'nombre', 'descripcion', 'cantidad_de_comics',
       'cantidad_de_series', 'cantidad_de_historias', 'fecha_modificacion',
       'fecha_insercion_bd'],
      dtype='object')
[2023-08-01 03:25:54,237] {python.py:173} INFO - Done. Returned value was: None
[2023-08-01 03:25:54,255] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=etl_api_marvel_hacia_aws_redshift_multitask, task_id=cargar_data, execution_date=20230801T032335, start_date=20230801T032542, end_date=20230801T032554
[2023-08-01 03:25:54,297] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-08-01 03:25:54,330] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:202: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2023-08-01 03:25:54,331] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:202: AirflowContextDeprecationWarning: Accessing 'next_execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_end' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2023-08-01 03:25:54,332] {logging_mixin.py:115} INFO - <TaskInstance: etl_api_marvel_hacia_aws_redshift_multitask.cargar_data scheduled__2023-08-01T03:23:35.277444+00:00 [success]>
[2023-08-01 03:25:54,332] {taskinstance.py:1760} ERROR - Error when executing on_success_callback
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1758, in _run_finished_callback
    task.on_success_callback(context)
  File "/opt/airflow/dags/dag_etl_multiple_tasks.py", line 89, in send_mail_success
    print(taskInstance.TR)
AttributeError: 'TaskInstance' object has no attribute 'TR'
[2023-08-01 03:25:54,349] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
